TheatreApp/Models/SeancesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.DTO;

namespace TheatreApp.Models
{
    public class SeancesViewModel
    {
        [Display(Name = "Спектакль")]
        public string SpectacleName { get; set; }

        [HiddenInput(DisplayValue = false)]
        public Guid SpectacleId { get; set; }

        public IEnumerable<SeanceDTO> Seances { get; set; }
    }
}

TheatreApp/Areas/Admin/Controllers/SeanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.DTO;
using BusinessLayer.Interfaces;

namespace TheatreApp.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class SeanceController : Controller
    {
        private readonly ISeanceService mSeanceService;
        private readonly ISpectacleService mSpectacleService;
        private readonly ISeanceChangedNotificationService mNotificationService;

        public SeanceController(ISeanceService seanceService, ISpectacleService spectacleService, ISeanceChangedNotificationService notificationService)
        {
            mSeanceService = seanceService;
            mSpectacleService = spectacleService;
            mNotificationService = notificationService;
        }

        public ActionResult Edit(Guid id)
        {
            var seance = mSeanceService.GetById(id);
            if (seance == null) HttpNotFound();
            return View(seance);
        }

        [HttpPost, ActionName("Edit")]
        public ActionResult EditConfirm(SeanceDTO seance)
        {
            if (ModelState.IsValid)
            {
                mNotificationService.NotificateOnUpdate(seance.Id, seance.Date);
                mSeanceService.Update(seance);
                return RedirectToAction("Seances", "Spectacle", new {id = seance.SpectacleId});
            }
            return View(seance);
        }

        public ActionResult Create(Guid spectacleId)
        {
            var spectacle = mSpectacleService.GetById(spectacleId);
            if (spectacle == null) return HttpNotFound();
            SeanceDTO dto = new SeanceDTO(true){SpectacleId = spectacleId, SpectacleName = spectacle.Name};
            return View(dto);
        }

        [HttpPost]
        public ActionResult Create(SeanceDTO seance)
        {
            if (ModelState.IsValid)
            {
                mSeanceService.Add(seance);
                return RedirectToAction("Seances", "Spectacle", new { id = seance.SpectacleId });
            }
            return View(seance);
        }

        public ActionResult Delete(Guid id)
        {

            var seance = mSeanceService.GetById(id);
            if (seance == null) HttpNotFound();
            return View(seance);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(Guid seanceId, Guid spectacleId)
        {
            mNotificationService.NotificateOnRemove(seanceId);
            mSeanceService.Remove(seanceId);
            return RedirectToAction("Seances", "Spectacle", new { id = spectacleId });
        }

        protected override void Dispose(bool disposing)
        {
            mSeanceService.Dispose();
            mSpectacleService.Dispose();
            mNotificationService.Dispose();
            base.Dispose(disposing);
        }
    }
}

TheatreApp/Controllers/SeanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using BusinessLayer.Interfaces;
using TheatreApp.Models;

namespace TheatreApp.Controllers
{
    public class SeanceController : ApiController
    {
        private const int PageSize = 5;
        private readonly ISeanceService mSeanceService;

        public SeanceController(ISeanceService seanceService)
        {
            mSeanceService = seanceService;
        }

        [HttpGet]
        public AfficheViewModel Affiche(int? page, Guid? spectacleId, DateTime? date)
        {
            var pageDto = mSeanceService.GetPage(page.GetValueOrDefault(), PageSize, spectacleId, date);

            var vm = new AfficheViewModel(pageDto.Page, page.GetValueOrDefault(),
                (int)Math.Ceiling((decimal)pageDto.Total / PageSize));
            return vm;
        }
    }
}

TheatreApp/Areas/Admin/Views/Seance/Create.cshtml
@model BusinessLayer.DTO.SeanceDTO

@{

    ViewBag.Title = "Сеанс";
}

<div class="col-md-6 col-md-offset-3">
    <h2>Добавление сеанса на спектакль: @Model.SpectacleName</h2>
    @using (Html.BeginForm("Create", "Seance", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        Html.RenderPartial("EditSeance", Model);
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    }
</div>

TheatreApp/Areas/Admin/Views/Seance/Delete.cshtml
@model BusinessLayer.DTO.SeanceDTO

@{
    ViewBag.Title = "Удаление";
}

<div class="col-md-6 col-md-offset-3">
    <h2>Удалить сеанс на спектакль '@Model.SpectacleName'?</h2>
    <h4>@Model.Date.ToString("f")</h4>
    @using (Html.BeginForm("Delete", "Seance", new { seanceId = Model.Id, spectacleId = Model.SpectacleId }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Удалить" class="btn btn-default" />
            </div>
        </div>
    }
</div>

TheatreApp/Areas/Admin/Views/Seance/Edit.cshtml
@model BusinessLayer.DTO.SeanceDTO

@{
    
    ViewBag.Title = "Сеанс";
}

<div class="col-md-6 col-md-offset-3">
    <h2>Редактирование сеанса на спектакль @Model.SpectacleName</h2>
    @using (Html.BeginForm("Edit", "Seance", FormMethod.Post, new {@class = "form-horizontal", role = "form"}))
    {
        Html.RenderPartial("EditSeance", Model);
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default"/>
            </div>
        </div>
    }
</div>

TheatreApp/Areas/Admin/Views/Seance/EditSeance.cshtml
@model BusinessLayer.DTO.SeanceDTO


@if (!ViewData.ModelState.IsValid)
{
    <div class="form-group">
        @Html.ValidationSummary(false, null, new { @class = "alert alert-danger" })
    </div>
}

<div class="form-group">
    @Html.HiddenFor(a => a.Id)
    @Html.HiddenFor(a => a.SpectacleName)
    @Html.HiddenFor(a => a.SpectacleId)
</div>


<div class="form-group">
    @Html.LabelFor(a => a.TicketsCount, new {@class = "col-md-2 control-label"})
    <div class="col-md-10">
        @Html.TextBoxFor(a => a.TicketsCount, new { @class = "form-control", Style = "max-width: 1000px;" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(a => a.Date, new { @class = "col-md-2 control-label" })
    <div class="col-md-10">
        <div class="input-group date" id="datetimepicker2">
            @Html.TextBoxFor(a => a.Date, new { @class = "form-control", Style = "max-width: 1000px;" })
            <div class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </div>
        </div>
    </div>
    <script type="text/javascript">
    $(function () {
        $('#datetimepicker2').datetimepicker({
            locale: 'ru'
        });
    });
    </script>
</div>