TheatreApp/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using BusinessLayer.Interfaces;
using DataAccessLayer.Entities;
using TheatreApp.Models;

namespace TheatreApp.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class HomeController : Controller
    {
        private readonly ISpectacleService mSpectacleService;

        public HomeController(ISpectacleService spectacleService)
        {
            mSpectacleService = spectacleService;
        }

        // GET: Admin/Home
        public ActionResult Index()
        {

            var spectacles = mSpectacleService.GetAll();
            return View(spectacles);
        }

        protected override void Dispose(bool disposing)
        {
            mSpectacleService.Dispose();
            base.Dispose(disposing);
        }
    }
}

TheatreApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.DTO;
using BusinessLayer.Interfaces;
using TheatreApp.Models;

namespace TheatreApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

TheatreApp/Controllers/SpectacleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using BusinessLayer.DTO;
using BusinessLayer.Interfaces;

namespace TheatreApp.Controllers
{
    public class SpectacleController : ApiController
    {
        private readonly ISpectacleService mSpectacleService;
        private readonly ISeanceService mSeanceService;

        public SpectacleController(ISpectacleService spectacleService, ISeanceService seanceService)
        {
            mSpectacleService = spectacleService;
            mSeanceService = seanceService;
        }

        [HttpGet]
        [ActionName("spectacles")]
        public IEnumerable<SpectacleDTO> Spectacles()
        {
            var spectacles = mSpectacleService.GetAll();
            return spectacles;
        }

        [HttpGet]
        [ActionName("dates")]
        public IEnumerable<DateTime> Dates(Guid? id)
        {
            IEnumerable<SeanceDTO> seances;
            seances = id.HasValue
                ? mSeanceService.GetSeancesBySpectacle(id.Value)
                : mSeanceService.GetAll();
            var dates = seances.Select(a => a.Date)
                .GroupBy(a => new { a.Year, a.Month, a.Day })
                .Select(a => new DateTime(a.Key.Year, a.Key.Month, a.Key.Day))
                .ToList();
            return dates;
        } 
    }
}

TheatreApp/Areas/Admin/Views/Home/Index.cshtml
@using TheatreApp.Models
@model IEnumerable<BusinessLayer.DTO.SpectacleDTO>
@{
    ViewBag.Title = "Спектакли";
}

<div class="col-md-8 col-md-offset-2">
    <h3>Список спектаклей</h3>
    @Html.ActionLink("Добавить спектакль", "Create", "Spectacle", null, new {@class = "btn btn-default"})
    <table class="table">
        <tr>
            <th>Название</th>
            <th></th>
            <th></th>
        </tr>
        @foreach (var spectacle in Model)
        {
            <tr>
                <td>@spectacle.Name</td>
                <td>@Html.ActionLink("Сеансы", "Seances", "Spectacle", new {id = spectacle.Id}, new {@class = "btn btn-default"})</td>
                <td>
                    @Html.ActionLink("Редактировать", "Edit", "Spectacle", new {id = spectacle.Id}, new {@class = "btn btn-default"})
                    @Html.ActionLink("Удалить", "Delete", "Spectacle", new {id = spectacle.Id}, new {@class = "btn btn-default"})
                </td>
            </tr>
        }
    </table>
</div>